FROM qmcgaw/latexdevcontainer

RUN apt update -y 
RUN apt install curl wget vim fontconfig && sudo wget -P /usr/share/fonts https://github.com/dolbydu/font/raw/master/unicode/FangSong.ttf https://github.com/dolbydu/font/raw/master/unicode/SimSun.ttc https://github.com/dolbydu/font/raw/master/unicode/SimHei.ttf https://github.com/dolbydu/font/raw/master/unicode/Kaiti.ttf  https://www.freebestfonts.com/yone//down/times.ttf


