% Date: 2023/03/04
% MDJNU.cls
\NeedsTeXFormat{LaTeX2e}[2023/03/04]
\ProvidesClass{MDJNU}[2023/03/04 v1.0.0 MDJNU class]


\LoadClass[a4paper,UTF8, zihao=-4,scheme=plain,fontset=none]{ctexbook}[2023/03/04]

\RequirePackage{graphicx}%用来插入图片
\RequirePackage{amsmath}%用来插入数学公式

\RequirePackage{geometry}%用来设置页面大小

\RequirePackage{fancyhdr}%用来设置页眉页脚

\RequireePackage{array}%用来设置表格 \toprule \midrule \bottomrule

\RequirePackage{booktabs}%用来设置表格

%\RequirePackage{tabularx}%用来设置表格
\RequirePackage{url}%用来设置网址
\RequirePackage{pdfpages} %用来设置pdf
\RequirePackage{notoccite}%用来设置参考文献
\RequirePackage{hyperref}%用来设置超链接



% 版面设计